version: "3.9"
services:
  api:
    build: .
    container_name: api-trepada-san-javier
    ports:
      - "4000:4000"
    environment:
      #- MONGO_URI=mongodb://localhost:27017/trepada-san-javier-BBDD
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
